import { CircuitDesign, CircuitElementType } from '@/api/types/circuit.types';
import { MeasurementBinding } from './types';

type Endpoint = { elementId: string; portId: string };

class UnionFind {
  private parent = new Map<string, string>();

  private find(x: string): string {
    if (!this.parent.has(x)) {
      this.parent.set(x, x);
    }
    const p = this.parent.get(x)!;
    if (p !== x) {
      const root = this.find(p);
      this.parent.set(x, root);
      return root;
    }
    return p;
  }

  union(a: string, b: string) {
    const ra = this.find(a);
    const rb = this.find(b);
    if (ra !== rb) {
      this.parent.set(ra, rb);
    }
  }

  toGroups(): Map<string, string[]> {
    const groups = new Map<string, string[]>();
    for (const key of this.parent.keys()) {
      const root = this.find(key);
      if (!groups.has(root)) groups.set(root, []);
      groups.get(root)!.push(key);
    }
    return groups;
  }
}

const getEndpointKey = (endpoint: Endpoint) => `${endpoint.elementId}:${endpoint.portId}`;

const orderPortsForElement = (type: CircuitElementType, ports: Endpoint[], portIdToNet: Record<string, string>) => {
  const portMap = (pid: string) => portIdToNet[getEndpointKey({ elementId: '', portId: pid })];
  switch (type) {
    case CircuitElementType.RESISTOR:
    case CircuitElementType.CAPACITOR:
    case CircuitElementType.INDUCTOR:
      return ports.slice(0, 2).map(p => portIdToNet[getEndpointKey(p)]);
    case CircuitElementType.VOLTAGE_SOURCE:
    case CircuitElementType.CURRENT_SOURCE: {
      const pos = ports.find(p => p.portId === 'positive') || ports[0];
      const neg = ports.find(p => p.portId === 'negative') || ports[1] || ports[0];
      return [portIdToNet[getEndpointKey(pos)], portIdToNet[getEndpointKey(neg)]];
    }
    case CircuitElementType.DIODE: {
      const anode = ports.find(p => p.portId === 'anode') || ports[0];
      const cathode = ports.find(p => p.portId === 'cathode') || ports[1] || ports[0];
      return [portIdToNet[getEndpointKey(anode)], portIdToNet[getEndpointKey(cathode)]];
    }
    case CircuitElementType.OPAMP: {
      const in1 = ports.find(p => p.portId === 'input1') || ports[0];
      const in2 = ports.find(p => p.portId === 'input2') || ports[1] || ports[0];
      const out = ports.find(p => p.portId === 'output') || ports[2] || ports[0];
      return [portIdToNet[getEndpointKey(in1)], portIdToNet[getEndpointKey(in2)], portIdToNet[getEndpointKey(out)]];
    }
    case CircuitElementType.AMMETER:
    case CircuitElementType.VOLTMETER:
      return ports.slice(0, 2).map(p => portIdToNet[getEndpointKey(p)]);
    case CircuitElementType.OSCILLOSCOPE: {
      const ch1 = ports.find(p => p.portId === 'channel1') || ports[0];
      const ch2 = ports.find(p => p.portId === 'channel2') || ports[1] || ports[0];
      const gnd = ports.find(p => p.portId === 'ground');
      return [
        portIdToNet[getEndpointKey(ch1)],
        portIdToNet[getEndpointKey(ch2)],
        gnd ? portIdToNet[getEndpointKey(gnd)] : '0',
      ];
    }
    default:
      return ports.map(p => portIdToNet[getEndpointKey(p)]);
  }
};

export const buildNetlist = (design: CircuitDesign) => {
  const uf = new UnionFind();
  const groundEndpoints = new Set<string>();

  design.connections.forEach(conn => {
    const sourceKey = getEndpointKey({ elementId: conn.source.elementId, portId: conn.source.portId });
    const targetKey = getEndpointKey({ elementId: conn.target.elementId, portId: conn.target.portId });
    uf.union(sourceKey, targetKey);
  });

  // 标记接地端口
  design.elements.forEach(el => {
    if (el.type === CircuitElementType.GROUND && el.ports?.length > 0) {
      el.ports.forEach(p => groundEndpoints.add(getEndpointKey({ elementId: el.id, portId: p.id })));
    }
  });

  // 建立 net 名称映射
  const groups = uf.toGroups();
  const rootToNet = new Map<string, string>();
  let netIndex = 1;

  for (const [root, members] of groups.entries()) {
    const hasGround = members.some(m => groundEndpoints.has(m));
    rootToNet.set(root, hasGround ? '0' : `N${netIndex++}`);
  }

  const endpointToNet: Record<string, string> = {};
  for (const [root, members] of groups.entries()) {
    const netName = rootToNet.get(root)!;
    members.forEach(m => { endpointToNet[m] = netName; });
  }

  const lines: string[] = [];
  const bindings: MeasurementBinding[] = [];

  lines.push('* Auto-generated by DrawSee');
  lines.push('.option numdgt=6');

  design.elements.forEach(el => {
    const ports = (el.ports || []).map(p => ({ elementId: el.id, portId: p.id }));
    const nets = orderPortsForElement(el.type as CircuitElementType, ports, endpointToNet);
    const value = el.value || el.properties?.value || '';
    const label = el.label || el.properties?.label || el.id;

    switch (el.type) {
      case CircuitElementType.RESISTOR:
        lines.push(`R${label} ${nets[0]} ${nets[1]} ${value || '1k'}`);
        break;
      case CircuitElementType.CAPACITOR:
        lines.push(`C${label} ${nets[0]} ${nets[1]} ${value || '1u'}`);
        break;
      case CircuitElementType.INDUCTOR:
        lines.push(`L${label} ${nets[0]} ${nets[1]} ${value || '1m'}`);
        break;
      case CircuitElementType.VOLTAGE_SOURCE:
        lines.push(`V${label} ${nets[0]} ${nets[1]} ${value || '5'}`);
        break;
      case CircuitElementType.CURRENT_SOURCE:
        lines.push(`I${label} ${nets[0]} ${nets[1]} ${value || '0.01'}`);
        break;
      case CircuitElementType.DIODE:
        lines.push(`D${label} ${nets[0]} ${nets[1]} DDEFAULT`);
        break;
      case CircuitElementType.OPAMP:
        // 简化模型：理想运放，使用受控源近似
        lines.push(`E${label} ${nets[2]} 0 ${nets[0]} ${nets[1]} 1e6`);
        break;
      case CircuitElementType.AMMETER: {
        const sourceName = `VAM${label}`;
        lines.push(`${sourceName} ${nets[0]} ${nets[1]} 0`);
        bindings.push({
          elementId: el.id,
          elementType: el.type,
          label,
          nets,
          measureKey: `I(${sourceName})`,
        });
        break;
      }
      case CircuitElementType.VOLTMETER: {
        bindings.push({
          elementId: el.id,
          elementType: el.type,
          label,
          nets,
          measureKey: `${nets[0]}-${nets[1]}`,
        });
        break;
      }
      case CircuitElementType.OSCILLOSCOPE: {
        bindings.push({
          elementId: el.id,
          elementType: el.type,
          label,
          nets,
          measureKey: `${nets[0]}-${nets[2] || '0'}`,
          channels: [nets[0], nets[1], nets[2] || '0'],
        });
        break;
      }
      default:
        break;
    }
  });

  lines.push('.tran 0.1ms 10ms');
  lines.push('.model DDEFAULT D');
  lines.push('.end');

  return {
    netlist: lines.join('\n'),
    bindings,
    nets: endpointToNet,
  };
};
