import { CircuitDesign } from '@/api/types/circuit.types';

// 导出格式枚举
export type ExportFormat = 'JSON' | 'SPICE' | 'SVG' | 'PNG' | 'PDF';

// 导出选项接口
export interface ExportOptions {
  format: ExportFormat;
  includeMetadata?: boolean;
  includeSimulationData?: boolean;
  resolution?: number;
  backgroundColor?: string;
  showGrid?: boolean;
  showLabels?: boolean;
}

/**
 * 专业级电路导入导出工具
 */
export class CircuitImportExport {
  /**
   * 导出电路设计
   * @param circuitDesign 电路设计数据
   * @param format 导出格式
   * @param options 导出选项
   */
  static exportCircuit(circuitDesign: CircuitDesign, format: ExportFormat, options?: Partial<ExportOptions>) {
    const exportOptions: ExportOptions = {
      format,
      includeMetadata: true,
      includeSimulationData: false,
      resolution: 300,
      backgroundColor: '#ffffff',
      showGrid: true,
      showLabels: true,
      ...options,
    };

    switch (format) {
      case 'JSON':
        this.exportAsJSON(circuitDesign, exportOptions);
        break;
      case 'SPICE':
        this.exportAsSPICE(circuitDesign, exportOptions);
        break;
      case 'SVG':
        this.exportAsSVG(circuitDesign, exportOptions);
        break;
      case 'PNG':
        this.exportAsPNG(circuitDesign, exportOptions);
        break;
      case 'PDF':
        this.exportAsPDF(circuitDesign, exportOptions);
        break;
      default:
        throw new Error(`不支持的导出格式: ${format}`);
    }
  }

  /**
   * 导出为JSON格式
   */
  private static exportAsJSON(circuitDesign: CircuitDesign, options: ExportOptions) {
    const exportData = {
      version: '1.0',
      metadata: options.includeMetadata ? circuitDesign.metadata : undefined,
      elements: circuitDesign.elements,
      connections: circuitDesign.connections,
      exportInfo: {
        timestamp: new Date().toISOString(),
        format: 'JSON',
        version: '1.0',
      },
    };

    const jsonString = JSON.stringify(exportData, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = `${circuitDesign.metadata.title || 'circuit'}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * 导出为SPICE格式
   */
  private static exportAsSPICE(circuitDesign: CircuitDesign, options: ExportOptions) {
    let spiceContent = '';
    
    // 添加标题和注释
    spiceContent += `* ${circuitDesign.metadata.title}\n`;
    spiceContent += `* ${circuitDesign.metadata.description}\n`;
    spiceContent += `* Generated by DrawSee Circuit Designer\n`;
    spiceContent += `* ${new Date().toISOString()}\n\n`;

    // 添加元件定义
    circuitDesign.elements.forEach(element => {
      const spiceLine = this.convertElementToSPICE(element);
      if (spiceLine) {
        spiceContent += spiceLine + '\n';
      }
    });

    spiceContent += '\n';

    // 添加分析命令
    spiceContent += '.tran 0.1 1\n'; // 瞬态分析
    spiceContent += '.dc V1 0 5 0.1\n'; // DC扫描
    spiceContent += '.ac dec 10 1 1e6\n'; // AC分析
    spiceContent += '.end\n';

    const blob = new Blob([spiceContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = `${circuitDesign.metadata.title || 'circuit'}.sp`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * 导出为SVG格式
   */
  private static exportAsSVG(circuitDesign: CircuitDesign, options: ExportOptions) {
    // 计算画布尺寸
    const bounds = this.calculateBounds(circuitDesign.elements);
    const width = Math.max(bounds.width + 100, 800);
    const height = Math.max(bounds.height + 100, 600);

    let svgContent = `<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">\n`;
    
    // 添加背景
    svgContent += `  <rect width="${width}" height="${height}" fill="${options.backgroundColor}"/>\n`;
    
    // 添加网格
    if (options.showGrid) {
      svgContent += this.generateSVGGrid(width, height);
    }

    // 添加元件
    circuitDesign.elements.forEach(element => {
      const svgElement = this.convertElementToSVG(element, options);
      if (svgElement) {
        svgContent += svgElement;
      }
    });

    // 添加连接线
    circuitDesign.connections.forEach(connection => {
      const svgConnection = this.convertConnectionToSVG(connection, circuitDesign.elements);
      if (svgConnection) {
        svgContent += svgConnection;
      }
    });

    svgContent += '</svg>';

    const blob = new Blob([svgContent], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = `${circuitDesign.metadata.title || 'circuit'}.svg`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * 导出为PNG格式
   */
  private static exportAsPNG(circuitDesign: CircuitDesign, options: ExportOptions) {
    // 使用html2canvas或类似库将SVG转换为PNG
    // 这里简化实现，实际需要更复杂的转换逻辑
    console.log('PNG导出功能需要html2canvas库支持');
  }

  /**
   * 导出为PDF格式
   */
  private static exportAsPDF(circuitDesign: CircuitDesign, options: ExportOptions) {
    // 使用jsPDF或类似库生成PDF
    // 这里简化实现，实际需要更复杂的PDF生成逻辑
    console.log('PDF导出功能需要jsPDF库支持');
  }

  /**
   * 导入电路设计
   * @param file 文件对象
   * @returns Promise<CircuitDesign>
   */
  static async importCircuit(file: File): Promise<CircuitDesign> {
    const fileExtension = file.name.split('.').pop()?.toLowerCase();
    
    switch (fileExtension) {
      case 'json':
        return this.importFromJSON(file);
      case 'sp':
      case 'spice':
        return this.importFromSPICE(file);
      default:
        throw new Error(`不支持的文件格式: ${fileExtension}`);
    }
  }

  /**
   * 从JSON文件导入
   */
  private static async importFromJSON(file: File): Promise<CircuitDesign> {
    const text = await file.text();
    const data = JSON.parse(text);
    
    // 验证数据结构
    if (!data.elements || !data.connections) {
      throw new Error('无效的电路设计文件格式');
    }

    return {
      elements: data.elements,
      connections: data.connections,
      metadata: data.metadata || {
        title: file.name.replace('.json', ''),
        description: '从JSON文件导入的电路设计',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    };
  }

  /**
   * 从SPICE文件导入
   */
  private static async importFromSPICE(file: File): Promise<CircuitDesign> {
    const text = await file.text();
    const lines = text.split('\n');
    
    const elements: any[] = [];
    const connections: any[] = [];
    let elementId = 1;

    lines.forEach(line => {
      const trimmedLine = line.trim();
      
      // 跳过注释和空行
      if (trimmedLine.startsWith('*') || trimmedLine === '') {
        return;
      }

      // 解析SPICE元件
      const element = this.parseSPICEElement(trimmedLine, elementId++);
      if (element) {
        elements.push(element);
      }
    });

    return {
      elements,
      connections,
      metadata: {
        title: file.name.replace(/\.(sp|spice)$/, ''),
        description: '从SPICE文件导入的电路设计',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    };
  }

  /**
   * 将元件转换为SPICE格式
   */
  private static convertElementToSPICE(element: any): string {
    switch (element.type) {
      case 'resistor':
        return `R${element.id} ${element.ports[0].id} ${element.ports[1].id} ${element.value}`;
      case 'capacitor':
        return `C${element.id} ${element.ports[0].id} ${element.ports[1].id} ${element.value}`;
      case 'inductor':
        return `L${element.id} ${element.ports[0].id} ${element.ports[1].id} ${element.value}`;
      case 'voltage_source':
        return `V${element.id} ${element.ports[0].id} ${element.ports[1].id} DC ${element.value}`;
      case 'current_source':
        return `I${element.id} ${element.ports[0].id} ${element.ports[1].id} DC ${element.value}`;
      default:
        return '';
    }
  }

  /**
   * 将元件转换为SVG格式
   */
  private static convertElementToSVG(element: any, options: ExportOptions): string {
    const x = element.position.x;
    const y = element.position.y;
    
    switch (element.type) {
      case 'resistor':
        return `  <rect x="${x}" y="${y}" width="60" height="20" fill="none" stroke="black" stroke-width="2"/>\n`;
      case 'capacitor':
        return `  <line x1="${x}" y1="${y}" x2="${x+20}" y2="${y}" stroke="black" stroke-width="2"/>\n  <line x1="${x+40}" y1="${y}" x2="${x+60}" y2="${y}" stroke="black" stroke-width="2"/>\n`;
      case 'voltage_source':
        return `  <circle cx="${x+30}" cy="${y+30}" r="30" fill="none" stroke="black" stroke-width="2"/>\n`;
      default:
        return '';
    }
  }

  /**
   * 将连接转换为SVG格式
   */
  private static convertConnectionToSVG(connection: any, elements: any[]): string {
    const sourceElement = elements.find(e => e.id === connection.sourceElementId);
    const targetElement = elements.find(e => e.id === connection.targetElementId);
    
    if (sourceElement && targetElement) {
      const x1 = sourceElement.position.x + 30;
      const y1 = sourceElement.position.y + 10;
      const x2 = targetElement.position.x + 30;
      const y2 = targetElement.position.y + 10;
      
      return `  <line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="black" stroke-width="2"/>\n`;
    }
    
    return '';
  }

  /**
   * 计算元件边界
   */
  private static calculateBounds(elements: any[]): { width: number; height: number } {
    if (elements.length === 0) {
      return { width: 0, height: 0 };
    }

    const xCoords = elements.map(e => e.position.x);
    const yCoords = elements.map(e => e.position.y);
    
    const minX = Math.min(...xCoords);
    const maxX = Math.max(...xCoords);
    const minY = Math.min(...yCoords);
    const maxY = Math.max(...yCoords);

    return {
      width: maxX - minX,
      height: maxY - minY,
    };
  }

  /**
   * 生成SVG网格
   */
  private static generateSVGGrid(width: number, height: number): string {
    let grid = '';
    const gridSize = 20;
    
    for (let x = 0; x <= width; x += gridSize) {
      grid += `  <line x1="${x}" y1="0" x2="${x}" y2="${height}" stroke="#e5e7eb" stroke-width="1"/>\n`;
    }
    
    for (let y = 0; y <= height; y += gridSize) {
      grid += `  <line x1="0" y1="${y}" x2="${width}" y2="${y}" stroke="#e5e7eb" stroke-width="1"/>\n`;
    }
    
    return grid;
  }

  /**
   * 解析SPICE元件
   */
  private static parseSPICEElement(line: string, id: number): any {
    const parts = line.split(/\s+/);
    if (parts.length < 4) return null;

    const type = parts[0][0].toLowerCase();
    const node1 = parts[1];
    const node2 = parts[2];
    const value = parts[3];

    const element = {
      id: `element_${id}`,
      type: '',
      position: { x: id * 100, y: 100 },
      rotation: 0,
      label: parts[0],
      value: value,
      ports: [
        { id: node1, name: '端口1', type: 'bidirectional', position: { side: 'left', x: 0, y: 50, align: 'center' } },
        { id: node2, name: '端口2', type: 'bidirectional', position: { side: 'right', x: 100, y: 50, align: 'center' } }
      ],
      properties: {}
    };

    switch (type) {
      case 'r':
        element.type = 'resistor';
        break;
      case 'c':
        element.type = 'capacitor';
        break;
      case 'l':
        element.type = 'inductor';
        break;
      case 'v':
        element.type = 'voltage_source';
        break;
      case 'i':
        element.type = 'current_source';
        break;
      default:
        return null;
    }

    return element;
  }
}